classroom/urls.py
from django.urls import path
from . import views
app_name='classroom'
urlpatterns = [
		#path('', views.home,name="home"),
			path('', views.classroom, name="classroom"),
	        path('question/', views.question, name="question"),
	        path('slide/', views.slide, name="slide"),
	        path('archive/', views.archive, name="archive"),
	        path('schedule/', views.schedule, name="schedule"),
	        
]

extras/urls.py
from django.urls import path
from . import views

urlpatterns = [
			path('', views.question, name="explore"),
			path('questions/', views.question, name="questions"),
			
	       
	        path('filter/', views.filter, name="filter"),
            path('resources/', views.resources, name="resources"),
	        
]

classroom/models.py
from django.db import models
import os
from django.utils import timezone
class Question(models.Model):
    heading=models.CharField(max_length=200)
    url=models.URLField(max_length=555,blank=True,null=True)
    question_date = models.DateTimeField(
            default=timezone.now)
    session=models.ForeignKey('Archive',on_delete=models.CASCADE,null=True)
    #tags = models.ManyToManyField('Tag')
    
    def __str__(self):
        return self.heading
class Slide(models.Model):
        heading=models.CharField(max_length=200,null=True)
        url=models.URLField(max_length=555,blank=True,null=True)
        question_date = models.DateTimeField(
            default=timezone.now)
        session=models.ForeignKey('Archive',on_delete=models.CASCADE,null=True)
class Archive(models.Model):
    session=models.CharField(max_length=60)  # since 2017-18 contains "-" character

    def __str__(self):
        return self.session

    class Meta:                   # ordering ka mtlb sorting (here sorting the results by headline)
        ordering = ('session',)        
class Schedule(models.Model):
    topic=models.CharField(max_length=200)
    duration=models.IntegerField(default=0)
    schedule_date = models.DateTimeField(
            default=timezone.now)

classroom/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from .models import Question,Slide,Archive,Schedule
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from fractalweb.models import ExtendedUser
@login_required
def classroom(request):
    return render(request, 'classroom/classroom.html', {})

@login_required
def question(request):
	# print(request.user)
	quote=ExtendedUser.objects.get(user=request.user).sessions
	print(quote,"\n\n\n\n\n")
	# for u in ulist:
	# 	if u.user==request.user:
	# 		quote=u.sessions
	# 		break

	if quote:
		
		p=Question.objects.filter(session__session=quote)
		
		context ={ 
			'filterap':p#,pp],
			#'filterapp':pp,
			}
		#return render(request,'classroom/ques_filter.html',context=context) 

	else:
		notfound="Enter Tags Or Category to filter"	
		return render(request,'classroom/questions.html', {'notfound':notfound})

	questionns_list=p.order_by('-question_date')
	q1=p.count()
	page = request.GET.get('page', 1)
	paginator = Paginator(questionns_list, 10)
	try:
		questionns= paginator.page(page)
	except PageNotAnInteger:
		questionns = paginator.page(1)
	except EmptyPage:
		questionns= paginator.page(paginator.num_pages)
	return render(request, 'classroom/questions.html', {'questionns': questionns,'q1':q1,'session':quote})
    #return render(request, 'classroom/question.html', {})

@login_required
def slide(request):
	quote=ExtendedUser.objects.get(user=request.user).sessions
	#print(quote,"\n\n\n\n\n")
	# for u in ulist:
	# 	if u.user==request.user:
	# 		quote=u.sessions
	# 		break

	if quote:
		
		p=Slide.objects.filter(session__session=quote)
		
		context ={ 
			'filterap':p#,pp],
			#'filterapp':pp,
			}
		#return render(request,'classroom/ques_filter.html',context=context) 

	else:
		notfound="Enter Tags Or Category to filter"	
		return render(request,'classroom/slide.html', {'notfound':notfound})

	slide_list=p.order_by('-question_date')

	page = request.GET.get('page', 1)
	paginator = Paginator(slide_list, 10)
	try:
		slide = paginator.page(page)
	except PageNotAnInteger:
		slide = paginator.page(1)
	except EmptyPage:
		slide = paginator.page(paginator.num_pages)
	return render(request, 'classroom/slide.html', {'slide': slide,'session':quote})

@login_required
def archive(request):

	if request.method == 'POST':	
		import requests
		u=ExtendedUser.objects.get(user=request.user)
		u.sessions=request.POST['quote']
		u.save()
	archive=Archive.objects.all().order_by('-id')
	# page = request.GET.get('page', 1)
	# paginator = Paginator(archive_list, 20)
	# try:
	# 	archive = paginator.page(page)
	# except PageNotAnInteger:
	# 	archive= paginator.page(1)
	# except EmptyPage:
	# 	archive= paginator.page(paginator.num_pages)
	return render(request, 'classroom/archive.html', {'archive': archive})

@login_required
def schedule(request):
	schedule_list=Schedule.objects.all().order_by('-schedule_date')
	page = request.GET.get('page', 1)
	paginator = Paginator(schedule_list, 10)
	try:
		schedule= paginator.page(page)
	except PageNotAnInteger:
		schedule = paginator.page(1)
	except EmptyPage:
		schedule= paginator.page(paginator.num_pages)
	return render(request, 'classroom/schedule.html', {'schedule': schedule})
# Create your views here.
#@login_required
#def ques_filter(request):
	

classroom/templates/classroom/archive.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Archive</title>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/common.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

  <style>
    *:focus {
    outline: 0;
    outline: none;
    }
  </style>
</head>

<body>
	
 <nav class="navbar navbar-expand-sm bg-dark navbar-dark " style="margin-bottom: 5%" id="navbar">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="{% url 'home' %}">
    <img src="{% static 'images/logo.png' %}" alt="Fractal" style="width:40px;"> Fractal
  </a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse" id="collapsibleNavbar">

  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:question' %}">Questions</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:slide' %}">Slide</a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'classroom:archive' %}">Archive</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:schedule' %}">Schedule</a>
    </li>
    {% if request.user.is_superuser %}
     <li class="nav-item">
      <!--a class="nav-link" href="{% url 'classroom:slide' %}">Admin User</a-->
    </li>
    {% endif %}
  </ul>
<!--  
  
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="questions.html">Questions</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="slide.html">Slide</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="archive.html">Archive</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="schedule.html">Schedule</a>
    </li>
  </ul>
-->

<!-- Items to the right in navbar-->

 <ul class="navbar-nav ml-auto">
    {% if user.is_authenticated %}
    <li><p class="top-menu" style="color:white">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
    {% else %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'login' %}">Login<i class="fa fa-user"></i></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'signup' %}">Register<i class="fa fa-user-plus"></i>
</a>
    </li>
    {% endif %}
</ul>
</div>
</nav>

<div class="container">

  <h1>Collection of previous sessions at Fractal</h1>
    <hr/>
  <br>
</div>

<form method="POST" action="{% url 'classroom:archive' %}">
      {% csrf_token %}
    <div class="form-group">
    <label for="exampleFormControlSelect1">Example select</label>
    <div class='topbox-inner-right-small l-float'>
    <center><select size="1" class="form-control" id="exampleFormControlSelect1" name='quote' style="width:30%;text-align:center;overflow-y: auto;overflow-x: hidden;">
     {% for a in archive %}
          <tr>
           <option>{{ a.session }}</option>
            
          </tr>
          {% endfor %}
    </select></center></div>
  </div>
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">submit</button>
  
</form>
  
</div>
</body>
</html>

classroom/templates/classroom/classroom.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Questions</title>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  <style>
    *:focus {
    outline: 0;
    outline: none;
    }
  </style>
</head>

<body>
	
<!--	<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Fluid jumbotron</h1>
    <p class="lead">Your life is decided by the contents of this page.</p>
  </div>
</div>
-->	

  <nav class="navbar navbar-expand-sm bg-light navbar-light " style="margin-bottom: 10px">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="{% url  'home' %}">
    <img src="#" alt="Fractal" style="width:40px;">
  </a>
  
  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'classroom:question' %}">Questions</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:slide' %}">Slide</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:archive' %}">Archive</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:schedule' %}">Schedule</a>
    </li>
  </ul>

 <ul class="navbar-nav ml-auto">
    {% if user.is_authenticated %}
    <li><p class="top-menu" style="color:white">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
    {% else %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'login' %}">Login<i class="fa fa-user"></i></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'signup' %}">Register<i class="fa fa-user-plus"></i>
</a>
    </li>
    {% endif %}
</ul>
  
</nav>
<br>
<br>
<h1>_________Welome Students......#Happy_Learning :)_________</h1>

  <!--table
	<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">URL</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>google drive</td>
      <td>29/8/2018</td>
    </tr>
  </tbody>
</table -->

</body>
</html>

classroom/templates/classroom/questions.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Questions</title>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/common.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">


	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  <style>
    *:focus {
    outline: 0;
    outline: none;
    }
  </style>
</head>

<body>
	
<!--	<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Fluid jumbotron</h1>
    <p class="lead">Your life is decided by the contents of this page.</p>
  </div>
</div>
-->	

 <nav class="navbar navbar-expand-sm bg-dark navbar-dark " style="margin-bottom: 5%" id="navbar">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="{% url 'home' %}">
    <img src="{% static 'images/logo.png' %}" alt="Fractal" style="width:40px;"> Fractal
  </a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse" id="collapsibleNavbar">

  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'classroom:question' %}">Questions</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:slide' %}">Slide</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:archive' %}">Archive</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:schedule' %}">Schedule</a>
    </li>
  </ul>


<!-- Items to the right in navbar-->

 <ul class="navbar-nav ml-auto">
    {% if user.is_authenticated %}
    <li><p class="top-menu" style="color:white">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
    {% else %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'login' %}">Login<i class="fa fa-user"></i></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'signup' %}">Register<i class="fa fa-user-plus"></i>
</a>
    </li>
    {% endif %}
</ul>
</div>
</nav>

<div class="container">
  <h1>{{ session }}</h1>
  <hr/>
  <br>
</div>


<div class="container">
  <!--table-->
	<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Questions</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
    {% for quest in questionns %}
          <tr>
            <th scope="row">{{ forloop.counter0|add:questionns.start_index }}</th>
        

            <td><a href="{{quest.url}}" target="_Blank">{{quest.heading}}</a></td>
            <td>{{ quest.question_date}}</td>
          </tr>
       {% endfor %}
  </tbody>
</table>


<!--Paginator-->
<div class="container">
    <div class="text-center">
  {% if questionns.has_other_pages %}
      <ul class="pagination">
        {% if questionns.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ questionns.previous_page_number }} tabindex="-1"">Previous</a></li>
        {% else %}
          <li class="page-item disabled"><span class="page-link">Previous</span></li>
        {% endif %}
        {% for i in questionns.paginator.page_range %}
          {% if questionns.number == i %}
            <li class="page-item active "><span class="page-link">{{ i }} <span class="sr-only page-link">(current)</span></span></li>
          {% else %}
            <li class=" page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if questionns.has_next %}
          <li class="page-item" ><a class="page-link" href="?page={{ questionns.next_page_number }}" tabindex="-1">Next</a></li>
        {% else %}
          <li class="page-item disabled"><span class="page-link">Next</span></li>
        {% endif %}
      </ul>
    {% endif %}
  </div>
</div>

</body>
</html>

classroom/templates/classroom/schedule.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Schedule</title>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/common.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">


	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" ></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" ></script>
  <style>
    *:focus {
    outline: 0;
    outline: none;
    }
  </style>
</head>

<body>
	
<!--	<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Fluid jumbotron</h1>
    <p class="lead">Your life's schedule is decided by the contents of this page.</p>
  </div>
</div>
-->	

 <nav class="navbar navbar-expand-sm bg-dark navbar-dark " style="margin-bottom: 5%" id="navbar">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="{% url 'home' %}">
    <img src="{% static 'images/logo.png' %}" alt="Fractal" style="width:40px;"> Fractal
  </a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse" id="collapsibleNavbar">

  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:question' %}">Questions</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:slide' %}">Slide</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:archive' %}">Archive</a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'classroom:schedule' %}">Schedule</a>
    </li>
  </ul>


<!-- Items to the right in navbar-->
 <ul class="navbar-nav ml-auto">
    {% if user.is_authenticated %}
    <li><p class="top-menu" style="color:white">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
    {% else %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'login' %}">Login<i class="fa fa-user"></i></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'signup' %}">Register<i class="fa fa-user-plus"></i>
</a>
    </li>
    {% endif %}
</ul>
</div>
</nav>

<div class="container">
  <h1>2017-18</h1>
  <hr/>
  <br>
</div>

<div class="container">
  <!--table-->
	<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Topic</th>
      <th scope="col">Duration</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
    {% for ss in schedule %}
          <tr>
            <th scope="row">{{ forloop.counter0|add:schedule.start_index }}</th>
            <td>{{ ss.topic }}</td>
            <td>{{ ss.duration }}</td>
            <td>{{ss.schedule_date }}</td>
            
          </tr>
       {% endfor %}
  </tbody>
</table>
<div class="container">
    <div class="text-center">
  {% if schedule.has_other_pages %}
      <ul class="pagination">
        {% if schedule.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ schedule.previous_page_number }} tabindex="-1"">Previous</a></li>
        {% else %}
          <li class="page-item disabled"><span class="page-link">Previous</span></li>
        {% endif %}
        {% for i in schedule.paginator.page_range %}
          {% if schedule.number == i %}
            <li class="page-item active "><span class="page-link">{{ i }} <span class="sr-only page-link">(current)</span></span></li>
          {% else %}
            <li class=" page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if schedule.has_next %}
          <li class="page-item" ><a class="page-link" href="?page={{ schedule.next_page_number }}" tabindex="-1">Next</a></li>
        {% else %}
          <li class="page-item disabled"><span class="page-link">Next</span></li>
        {% endif %}
      </ul>
    {% endif %}
  </div>
</div>


</body>
</html>